// ~/clawd-saas-core/engine/worker.js
// PINO SAAS WORKER

const fs = require('fs');
const path = require('path');
const Database = require('better-sqlite3');

// 1. Load Config (Simulating a tenant)
const CONFIG_PATH = path.join(__dirname, '../config/template.json');
const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));

// 2. Connect DB
const DB_PATH = path.join(__dirname, '../db/pipeline.db');
const db = new Database(DB_PATH);

console.log('🕷️ PINO (SaaS) Started');
console.log(`🏢 Client: ${config.client_name}`);

// 3. Find Todo
const todo = db.prepare("SELECT * FROM articles WHERE status='todo' LIMIT 1").get();

if (!todo) {
  console.log('💤 No articles in todo queue.');
  process.exit(0);
}

console.log(`📝 Picking up article: ${todo.title}`);

// 4. Load Agent Prompt & Inject Config
let prompt = fs.readFileSync(path.join(__dirname, 'agents/pino-writer.md'), 'utf8');

// Replace placeholders
prompt = prompt.replace('{{PROJECT_CONFIG}}', JSON.stringify(config, null, 2));
prompt = prompt.replace('{{PROJECT_CONFIG.language}}', config.content_guidelines.language);
prompt = prompt.replace('{{PROJECT_CONFIG.writing.tone}}', config.content_guidelines.tone);
prompt = prompt.replace('{{PROJECT_CONFIG.writing.word_count}}', '1500-2000'); // Default
prompt = prompt.replace('{{PROJECT_CONFIG.writing.target_audience}}', 'Professionals'); // Default
prompt = prompt.replace('{{PROJECT_CONFIG.writing.forbidden}}', 'Generic AI phrases'); // Default

console.log('🤖 Prompt prepared with injected config.');

// 5. Simulate LLM Generation (Mock)
console.log('🚀 Calling LLM (Simulated)...');
const mockContent = `# ${todo.title}

This is a draft generated by Pino for ${config.client_name}.
Tone: ${config.content_guidelines.tone}
Language: ${config.content_guidelines.language}

## Introduction
Here is the intro...

## Section 1
Content...
`;

// 6. Save Result
db.prepare("UPDATE articles SET draft_md=?, status='review', claimed_by='pino', claimed_at=datetime('now') WHERE id=?")
  .run(mockContent, todo.id);

console.log('✅ Article saved as Draft (Status: review)!');
console.log('🎉 PINO WORK COMPLETE');
